modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/cao-awa/Calyx/issues"
license = "GPLv3"

[[mods]]
modId = "calyx"
version = "${version}"
displayName = "Calyx"
authors = "cao_awa"
description = '''

'''
#logoFile = ""

[[dependencies.calyx]]
modId = "neoforge"
type = "required"
versionRange = "[21.6.8-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.calyx]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.6]"
ordering = "NONE"
side = "BOTH"

#[[dependencies.calyx]]
#modId = "architectury"
#type = "required"
#versionRange = "[15.0.1,)"
#ordering = "AFTER"
#side = "BOTH"

[[mixins]]
config = "calyx.mixins.json"

[[accessTransformers]]
## The file is relative to the output directory of the resources, or the root path inside the jar when compiled
## The 'resources' directory represents the root output directory of the resources
file = "calyx_transformer.cfg"